Repository momodo-ToDoSupport/momodo_front, pull requests merged in 2023-08, with the labels that each got.

#4 Feature/ 유저정보관리
  package-lock.json
  package.json
  src/api/auth.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/store/authStore.ts
Labels: feature

#5 Feature/ TabBar Active 상태 구현
  public/images/chatIcon-active.svg
  public/images/chatIcon.svg
  public/images/feedIcon-active.svg
  public/images/feedIcon.svg
  public/images/homeIcon.svg
  public/images/todoIcon-active.svg
  public/images/todoIcon.svg
  src/components/TabBar.tsx
  src/components/TabBarIcon.tsx
  src/queryContext/Provider.tsx
Labels: feature

#6 Refact/카카오로그인
  src/app/kakaologin/page.tsx
  src/app/kakaosociallogin/page.tsx
  src/app/page.tsx
  src/components/Button.tsx
Labels: refact

#8 feature: TODO POST
  src/api/axios-api.ts
  src/api/todo.ts
  src/app/login/page.tsx
  src/components/TodoList/TodoForm.tsx
Labels: feature

#17 feature: mypage 접속시 유저 ID 렌더링
  src/app/login/page.tsx
  src/app/mytodo/page.tsx
  src/components/UserProfile/ProfileCard.tsx
  src/store/authStore.ts
Labels: feature

#21 Fix/카카오로그인
  src/app/kakaologin/page.tsx
  src/app/login/page.tsx
  src/app/mytodo/page.tsx
  src/components/UserProfile/ProfileCard.tsx
  src/service/kakao-login.ts
  src/store/authStore.ts
Labels: fix

#26 Feat : TodoList 기능 추가(duration: 반복주 적용, repeatDate: 반복요일) & TodoList생성시 Lists에 즉시반영
  src/components/TodoList/TodoForm.tsx
Labels: feature, refact
